### ISSUE TITLE
imp sort fail on windows 10

### ISSUE THREAD

**Issue by dufoli** [revelc/impsort-maven-plugin#38]
**Describe the bug**
when I run the mvn process-sources, I get an error on file because of line ending. If I delete few line it work again.

Failed to execute goal net.revelc.code:impsort-maven-plugin:1.4.1:sort (sort-imports) on project quarkus-cxf-deployment: Error reading file D:\src\quarkiverse-cxf\deployment\src\main\java\io\quarkiverse\cxf\deployment\QuarkusCxfProcessor.java: Unable to parse D:\src\quarkiverse-cxf\deployment\src\main\java\io\quarkiverse\cxf\deployment\QuarkusCxfProcessor.java

issue is on file :
https://github.com/quarkiverse/quarkiverse-cxf/blob/master/deployment/src/main/java/io/quarkiverse/cxf/deployment/QuarkusCxfProcessor.java
if I remove line 1425 to 1520
it work again.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 1.4.1
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Java version: 1.8.0_221, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_221\jre
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. git clone https://github.com/quarkiverse/quarkiverse-cxf.git
2. run mvn process-sources
3. see error

**Expected behavior**
import sorted and no error.

**Comment by dufoli** [comment]
here is stack trace
Caused by: java.io.IOException: Unable to parse D:\src\quarkiverse-cxf\deployment\src\main\java\io\quarkiverse\cxf\deployment\QuarkusCxfProcessor.java
    at net.revelc.code.impsort.ImpSort.lambda$parseFile$1 (ImpSort.java:88)
    at java.util.Optional.orElseThrow (Optional.java:290)
    at net.revelc.code.impsort.ImpSort.parseFile (ImpSort.java:88)
    at net.revelc.code.impsort.maven.plugin.AbstractImpSortMojo.lambda$execute$3 (AbstractImpSortMojo.java:228)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:184)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining (Spliterators.java:948)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:482)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:472)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:418)
    at java.util.stream.ReferencePipeline$7$1.accept (ReferencePipeline.java:270)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining (Spliterators.java:948)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:482)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:472)
    at java.util.stream.ReduceOps$ReduceTask.doLeaf (ReduceOps.java:747)
    at java.util.stream.ReduceOps$ReduceTask.doLeaf (ReduceOps.java:721)
    at java.util.stream.AbstractTask.compute (AbstractTask.java:316)
    at java.util.concurrent.CountedCompleter.exec (CountedCompleter.java:731)
    at java.util.concurrent.ForkJoinTask.doExec (ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask (ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker (ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run (ForkJoinWorkerThread.java:157)

**Comment by ctubbsii** [comment]
Can you try with the lastest SNAPSHOT version in the main branch? I think I may h ave already fixed some issues related to compiler compliance and line ending checks that were added in 1.4.1, but I haven't yet published the fix.

**Comment by martinaldrin** [comment]
I got the same issue, and I have now tested with latest SNAPSHOT and it works.
When can this fix be released?

**Comment by ctubbsii** [comment]
@martinaldrin I released 1.5.0 today. It should be available in Maven Central soon.

**Comment by martinaldrin** [comment]
Hi, it is still not available, so i guess something went wrong with the release.

**Comment by martinaldrin** [comment]
Sorry, it works. I guess it is just some delays until it shows up on https://mvnrepository.com/
